### ISSUE TITLE
4) Find the Asymmetry with MaxLike

### ISSUE THREAD

**Issue by IVAN-DPP** [IVAN-DPP/CodigoNickGui-o#7]
- [x] test the method MaxLike with ROOT::MATH::Minimizer
- [x] Apply this with the MaxLike function
- [x] Find the asymmetry Sigma
- [x] Compare the two methods

**Comment by IVAN-DPP** [comment]
We don't know which the parameters in the MaxLike function, but We already implemented the ROOT :: MATH :: Minimizer with the MaxLike function 3cdea8eb19733a76dfcbc131620362e47ed160ad

**Comment by KMRodriguez** [comment]
Now, we know these parameters:
x[o] is Sigma
x[1] is Phi_{0}

![Captura de pantalla de 2020-12-30 17-31-04](https://user-images.githubusercontent.com/48844741/103384565-d7d46b00-4ac4-11eb-9033-6cf87cb48b4e.png)
